# Generated by Django 5.1.15 on 2026-08-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("at", models.DateTimeField()),
                ("kind", models.CharField(max_length=32)),
                ("severity", models.CharField(default="info", max_length=7)),
                ("actor", models.CharField(blank=True, default="", max_length=150)),
                ("actor_ip", models.CharField(blank=True, default="", max_length=45)),
                ("target", models.CharField(blank=True, default="", max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["-id"],
            },
        ),
    ]
