"""Check profiles generated by lib/obfs.sh. Driven by tests/obfs.sh, not run alone.

Two passes over each profile. The first hands it to awg.validate, which is the
same code the panel saves through, so anything it rejects is a profile the
shell should never have produced. The second renders each imitation packet to
real bytes and parses it as the protocol it claims to be - a decoy that a
filter can tell is malformed is worse than no decoy, and the only way to know
is to try to read one.
"""

import os
import re
import struct
import sys

from awg import validate

# Everything the installed module supports on the release install.sh pins.
FEATURES = {
    "imitation_packets": True,
    "header_ranges": True,
    "header_protection_key": True,
    "content_padding": True,
    "timers": True,
    "random_trailers": True,
    "disable_cookies": True,
}

TAG = re.compile(r"<\s*(r|b)\s*([^>]*?)\s*>")

failures: list[str] = []


def fail(profile: int, message: str) -> None:
    failures.append(f"profile {profile}: {message}")


def render(spec: str) -> bytes:
    """The bytes the kernel would put on the wire for one imitation packet."""
    out = bytearray()
    for kind, arg in TAG.findall(spec):
        out += os.urandom(int(arg)) if kind == "r" else bytes.fromhex(arg[2:])
    return bytes(out)


def varint(buf: bytes, i: int) -> tuple[int, int]:
    count = 1 << (buf[i] >> 6)
    value = buf[i] & 0x3F
    for step in range(1, count):
        value = (value << 8) | buf[i + step]
    return value, i + count


def check_stun(b: bytes) -> None:
    kind, length = struct.unpack(">HH", b[:4])
    assert kind in (0x0001, 0x0101), f"message type {kind:#06x}"
    assert b[4:8] == bytes.fromhex("2112a442"), "wrong magic cookie"
    assert length == len(b) - 20, f"length says {length}, packet has {len(b) - 20}"
    i = 20
    while i < len(b):
        _kind, size = struct.unpack(">HH", b[i : i + 4])
        i += 4 + size + (-size % 4)
    assert i == len(b), "attributes overrun the packet"


def check_rtp(b: bytes) -> None:
    assert b[0] >> 6 == 2, "not RTP version 2"
    assert b[0] & 0x0F == 0, "claims CSRCs it does not carry"
    assert 96 <= b[1] & 0x7F <= 127, "payload type outside the dynamic range"
    assert len(b) >= 12, "shorter than an RTP header"


def check_quic_initial(b: bytes) -> None:
    assert b[0] & 0xC0 == 0xC0, "not a long header with the fixed bit set"
    assert (b[0] >> 4) & 0x03 == 0, "long header type is not Initial"
    assert b[1:5] == bytes.fromhex("00000001"), "not QUIC version 1"
    i = 5
    i += 1 + b[i]  # destination connection id
    i += 1 + b[i]  # source connection id
    token, i = varint(b, i)
    assert token == 0, "token length is not zero"
    length, i = varint(b, i)
    assert i + length == len(b), f"length says {length}, {len(b) - i} bytes follow"
    # RFC 9000 section 14.1: a client Initial that is not padded to 1200 bytes
    # is one no real client sends, and is the giveaway rather than the cover.
    assert len(b) >= 1200, f"Initial is {len(b)} bytes, under the 1200 minimum"


def check_quic_short(b: bytes) -> None:
    assert b[0] & 0xC0 == 0x40, "not a short header with the fixed bit set"


def check_dns(b: bytes) -> None:
    _txid, _flags, questions, answers, _authority, additional = struct.unpack(">HHHHHH", b[:12])
    i = 12
    for _ in range(questions):
        while b[i]:
            i += 1 + b[i]
        i += 1 + 4
    for _ in range(answers):
        assert b[i] & 0xC0 == 0xC0, "answer name is not a compression pointer"
        i += 2
        _t, _c, _ttl, rdlength = struct.unpack(">HHIH", b[i : i + 10])
        i += 10 + rdlength
    for _ in range(additional):
        assert b[i] == 0, "OPT record is not at the root name"
        i += 1
        kind, _udp, _ttl, rdlength = struct.unpack(">HHIH", b[i : i + 10])
        assert kind == 41, f"additional record type {kind}, expected OPT"
        i += 10 + rdlength
    assert i == len(b), "records overrun the packet"


# Which check to run is decided by the template, never by the rendered bytes:
# a DNS transaction ID is random, so a rendered packet can start like anything.
SHAPES = (
    ("<b 0x0001", check_stun),
    ("<b 0x0101", check_stun),
    ("<b 0xc3", check_quic_initial),
    ("<b 0x80", check_rtp),
    ("<b 0x43", check_quic_short),
    ("<b 0x53", check_quic_short),
    ("<b 0x63", check_quic_short),
    ("<b 0x73", check_quic_short),
    ("<r 2>", check_dns),
)


def check_packet(spec: str) -> None:
    for prefix, checker in SHAPES:
        if spec.startswith(prefix):
            checker(render(spec))
            return
    raise AssertionError(f"no shape recognises {spec[:24]!r}")


def check(number: int, values: dict[str, str]) -> None:
    errors = validate.validate_params(values, features=FEATURES)
    for key, message in sorted(errors.items()):
        fail(number, f"{key} rejected: {message}")
    for warning in validate.warnings_for(values):
        fail(number, f"warned: {warning}")

    # The key and the padding it is carried in are drawn in the same run, so the
    # only correct pairing is both or neither. A key over a prefix too short for
    # its nonce is not a weaker server, it is `awg setconf` returning EINVAL and
    # an interface that never comes up; a prefix long enough with no key is the
    # installer quietly declining to use the strongest setting it has.
    key = values.get("HeaderProtectionKey", "")
    short = validate.header_protection_short({**values, "HeaderProtectionKey": key or "x" * 44})
    if key and short:
        fail(number, f"{', '.join(short)} below the header protection floor, but a key was drawn")
    if not key and not short:
        fail(number, "the padding could carry a header protection key and none was drawn")

    # Drawn as a set or not at all: a config carrying three of the five timers
    # is one where the two the protocol falls back on were chosen by nobody.
    timers = validate.TIMER_PARAMS
    drawn = [name for name in timers if values.get(name)]
    if drawn and len(drawn) != len(timers):
        fail(number, f"only {len(drawn)} of {len(timers)} timers drawn: {drawn}")

    # Drawn on, and the assertion is that it stays drawn. It is the one setting
    # here with no value to check - the failure it guards against is not a bad
    # draw but a silent stop, a generator that quietly went back to leaving the
    # newest setting on the page off. "on" and not "off": off is spelled by
    # writing no line at all, and a written "off" is one every client config
    # would carry a meaningless copy of.
    trailers = values.get("RandomTrailers")
    if trailers != "on":
        fail(number, f"RandomTrailers={trailers!r}, expected 'on'")

    # The other half of that switch, and the reason it is safe to leave on. With
    # trailers the kernel accepts a handshake by minimum length rather than exact
    # length, so H1-H3 are all that separates a handshake from a data packet: the
    # share of the header space a range covers is the share of data packets
    # misfiled as handshakes and dropped, in both directions, with nothing in any
    # log. warnings_for above catches a width that has gone far enough to be
    # worth telling an operator about; this catches the drift long before that,
    # and catches it whether or not the switch above is still being drawn - the
    # two are one setting and only fail together.
    for name in ("H1", "H2", "H3", "H4"):
        bounds = validate._parse_range(values.get(name, ""))
        if bounds is None:
            fail(number, f"{name}={values.get(name)!r} is not a range")
            continue
        width = bounds[1] - bounds[0] + 1
        if not validate.H_WIDTH_LO <= width <= validate.H_WIDTH_HI:
            fail(
                number,
                f"{name} is {width} wide, outside "
                f"{validate.H_WIDTH_LO}-{validate.H_WIDTH_HI}",
            )

    if drawn:
        check_advanced_bands(number, values)


def check_advanced_bands(number: int, values: dict[str, str]) -> None:
    """The advanced values against the panel's own bands, read from the panel.

    validate_params above only enforces each parameter's hard bounds, which are
    far wider than the band a profile draws from - so it would pass a shell
    generator that had drifted a whole profile away from the Python one and
    still say the two agree. That gap is tolerable for the obfuscation bands,
    where both sides have quoted the same numbers since the beginning; it is not
    for these, which were copied across the two languages by hand and can only
    be kept in step by something that reads one and checks the other.

    ADVANCED_PROFILES["standard"] is the band, because install.sh offers no
    profile picker and standard is what lib/obfs.sh mirrors.
    """
    band = validate.ADVANCED_PROFILES["standard"]

    def ends(key: str) -> tuple[int, int]:
        """The two ends of a timer, whichever shape the shell wrote it in.

        Bare numbers are still legal and lib/obfs.sh still emits one when a band
        is too narrow to place a range inside, so this reads both rather than
        insisting on the dash.
        """
        parsed = validate._parse_range(values[key])
        if parsed is None:
            fail(number, f"{key}={values[key]!r} is neither a number nor a range")
            return (0, 0)
        return parsed

    def within(key: str, bounds: tuple[int, int]) -> tuple[int, int]:
        low, high = ends(key)
        if not bounds[0] <= low <= high <= bounds[1]:
            fail(number, f"{key}={low}-{high} is outside the panel's {bounds[0]}-{bounds[1]} band")
        # A range that collapsed to a point is the constant the ranges exist to
        # avoid, and a shell that has quietly stopped drawing them is the exact
        # drift this file is here to catch: the values would still validate, and
        # every server would still differ from every other, while the cadence on
        # each one went back to a metronome.
        if low == high and bounds[1] > bounds[0]:
            fail(number, f"{key}={low} was drawn as a single value inside a {bounds} band")
        return low, high

    rekey_after = within("RekeyAfterTime", band.rekey_after)
    rekey_timeout = within("RekeyTimeout", band.rekey_timeout)
    keepalive = within("KeepaliveTimeout", band.keepalive)
    within("MaxHandshakeAttempts", band.attempts)

    # Derived rather than drawn, so what is checked is the derivation: the three
    # timers a peer may spend on one rekey cycle, plus the profile's margin. The
    # tops of the three and the bottom of this one, which is the pairing
    # randomize_advanced uses and stricter than the kernel demands - see the
    # comment there.
    reject_lo, reject_hi = ends("RejectAfterTime")
    floor = rekey_after[1] + keepalive[1] + rekey_timeout[1]
    margin = reject_lo - floor
    if not band.margin[0] <= margin <= band.margin[1]:
        fail(number, f"RejectAfterTime sits {margin}s above the rekey cycle, outside {band.margin}")
    width = reject_hi - reject_lo
    if not band.margin[0] <= width <= band.margin[1]:
        fail(number, f"RejectAfterTime spans {width}s, outside the margin band {band.margin}")

    padding = values.get("ContentPaddingAddition", "")
    if padding:
        low, _, high = padding.partition("-")
        if not high:
            fail(number, f"ContentPaddingAddition={padding!r} is a number, not a range")
        else:
            within_pad = band.padding[0] <= int(high) <= band.padding[1]
            if not within_pad:
                fail(number, f"content padding top {high} is outside {band.padding}")
            if int(low) > int(high) // 3:
                fail(number, f"content padding floor {low} is not well below its top {high}")
            if int(high) < validate.PADDING_MULTIPLE:
                fail(
                    number,
                    f"content padding top {high} is under the {validate.PADDING_MULTIPLE}-byte rounding it replaces",
                )

    # Base64 and nothing else. validate accepts 64 hex characters as well,
    # because a key can be typed into the panel, but a key in a .conf file goes
    # through config.c's parse_key, which is key_from_base64 alone - the tools
    # carry a key_from_hex and use it only on the UAPI socket. A hex key in
    # awg0.conf is "Key is not the correct length or format" followed by
    # `awg setconf` refusing the whole file, so the installer has one spelling.
    key = values.get("HeaderProtectionKey", "")
    if key and not validate._B64_KEY_RE.match(key):
        fail(number, f"the header protection key is not the base64 `awg setconf` reads: {key!r}")

    packets = [values[f"I{n}"] for n in range(1, 6) if values.get(f"I{n}")]
    if not 3 <= len(packets) <= 5:
        fail(number, f"{len(packets)} imitation packets, expected 3 to 5")
    filled = [bool(values.get(f"I{n}")) for n in range(1, 6)]
    if filled != sorted(filled, reverse=True):
        fail(number, f"imitation slots have a gap: {filled}")

    for slot, spec in enumerate(packets, start=1):
        try:
            check_packet(spec)
        except (AssertionError, IndexError, struct.error, ValueError) as exc:
            fail(number, f"I{slot} does not parse: {exc}")


def main(path: str) -> int:
    with open(path) as handle:
        rows = [line.rstrip("\n") for line in handle if line.strip()]

    for number, row in enumerate(rows, start=1):
        values = dict(field.split("=", 1) for field in row.split("\t"))
        check(number, values)

    if failures:
        print(f"  FAIL  {len(failures)} problem(s) in {len(rows)} profiles")
        for line in failures[:20]:
            print(f"        {line}")
        return 1
    print(f"  ok    {len(rows)} profiles pass the panel validator and parse as their protocols")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1]))
