"""Check profiles generated by lib/obfs.sh. Driven by tests/obfs.sh, not run alone.

Two passes over each profile. The first hands it to awg.validate, which is the
same code the panel saves through, so anything it rejects is a profile the
shell should never have produced. The second renders each imitation packet to
real bytes and parses it as the protocol it claims to be - a decoy that a
filter can tell is malformed is worse than no decoy, and the only way to know
is to try to read one.
"""

import os
import re
import struct
import sys

from awg import validate

# Everything the installed module supports on the release install.sh pins.
FEATURES = {
    "imitation_packets": True,
    "header_ranges": True,
    "header_protection_key": True,
    "content_padding": True,
    "timers": True,
    "random_trailers": True,
}

TAG = re.compile(r"<\s*(r|b)\s*([^>]*?)\s*>")

failures: list[str] = []


def fail(profile: int, message: str) -> None:
    failures.append(f"profile {profile}: {message}")


def render(spec: str) -> bytes:
    """The bytes the kernel would put on the wire for one imitation packet."""
    out = bytearray()
    for kind, arg in TAG.findall(spec):
        out += os.urandom(int(arg)) if kind == "r" else bytes.fromhex(arg[2:])
    return bytes(out)


def varint(buf: bytes, i: int) -> tuple[int, int]:
    count = 1 << (buf[i] >> 6)
    value = buf[i] & 0x3F
    for step in range(1, count):
        value = (value << 8) | buf[i + step]
    return value, i + count


def check_stun(b: bytes) -> None:
    kind, length = struct.unpack(">HH", b[:4])
    assert kind in (0x0001, 0x0101), f"message type {kind:#06x}"
    assert b[4:8] == bytes.fromhex("2112a442"), "wrong magic cookie"
    assert length == len(b) - 20, f"length says {length}, packet has {len(b) - 20}"
    i = 20
    while i < len(b):
        _kind, size = struct.unpack(">HH", b[i : i + 4])
        i += 4 + size + (-size % 4)
    assert i == len(b), "attributes overrun the packet"


def check_rtp(b: bytes) -> None:
    assert b[0] >> 6 == 2, "not RTP version 2"
    assert b[0] & 0x0F == 0, "claims CSRCs it does not carry"
    assert 96 <= b[1] & 0x7F <= 127, "payload type outside the dynamic range"
    assert len(b) >= 12, "shorter than an RTP header"


def check_quic_initial(b: bytes) -> None:
    assert b[0] & 0xC0 == 0xC0, "not a long header with the fixed bit set"
    assert (b[0] >> 4) & 0x03 == 0, "long header type is not Initial"
    assert b[1:5] == bytes.fromhex("00000001"), "not QUIC version 1"
    i = 5
    i += 1 + b[i]  # destination connection id
    i += 1 + b[i]  # source connection id
    token, i = varint(b, i)
    assert token == 0, "token length is not zero"
    length, i = varint(b, i)
    assert i + length == len(b), f"length says {length}, {len(b) - i} bytes follow"
    # RFC 9000 section 14.1: a client Initial that is not padded to 1200 bytes
    # is one no real client sends, and is the giveaway rather than the cover.
    assert len(b) >= 1200, f"Initial is {len(b)} bytes, under the 1200 minimum"


def check_quic_short(b: bytes) -> None:
    assert b[0] & 0xC0 == 0x40, "not a short header with the fixed bit set"


def check_dns(b: bytes) -> None:
    _txid, _flags, questions, answers, _authority, additional = struct.unpack(">HHHHHH", b[:12])
    i = 12
    for _ in range(questions):
        while b[i]:
            i += 1 + b[i]
        i += 1 + 4
    for _ in range(answers):
        assert b[i] & 0xC0 == 0xC0, "answer name is not a compression pointer"
        i += 2
        _t, _c, _ttl, rdlength = struct.unpack(">HHIH", b[i : i + 10])
        i += 10 + rdlength
    for _ in range(additional):
        assert b[i] == 0, "OPT record is not at the root name"
        i += 1
        kind, _udp, _ttl, rdlength = struct.unpack(">HHIH", b[i : i + 10])
        assert kind == 41, f"additional record type {kind}, expected OPT"
        i += 10 + rdlength
    assert i == len(b), "records overrun the packet"


# Which check to run is decided by the template, never by the rendered bytes:
# a DNS transaction ID is random, so a rendered packet can start like anything.
SHAPES = (
    ("<b 0x0001", check_stun),
    ("<b 0x0101", check_stun),
    ("<b 0xc3", check_quic_initial),
    ("<b 0x80", check_rtp),
    ("<b 0x43", check_quic_short),
    ("<b 0x53", check_quic_short),
    ("<b 0x63", check_quic_short),
    ("<b 0x73", check_quic_short),
    ("<r 2>", check_dns),
)


def check_packet(spec: str) -> None:
    for prefix, checker in SHAPES:
        if spec.startswith(prefix):
            checker(render(spec))
            return
    raise AssertionError(f"no shape recognises {spec[:24]!r}")


def check(number: int, values: dict[str, str]) -> None:
    errors = validate.validate_params(values, features=FEATURES)
    for key, message in sorted(errors.items()):
        fail(number, f"{key} rejected: {message}")
    for warning in validate.warnings_for(values):
        fail(number, f"warned: {warning}")

    # The installer writes no header protection key, so nothing here needs the
    # padding floor yet - the panel turning one on later does, and by then these
    # numbers are already in awg0.conf. A server installed below the floor is one
    # where that button produces a config the kernel refuses.
    short = validate.header_protection_short({**values, "HeaderProtectionKey": "x" * 44})
    if short:
        fail(number, f"{', '.join(short)} below the header protection floor")

    packets = [values[f"I{n}"] for n in range(1, 6) if values.get(f"I{n}")]
    if not 3 <= len(packets) <= 5:
        fail(number, f"{len(packets)} imitation packets, expected 3 to 5")
    filled = [bool(values.get(f"I{n}")) for n in range(1, 6)]
    if filled != sorted(filled, reverse=True):
        fail(number, f"imitation slots have a gap: {filled}")

    for slot, spec in enumerate(packets, start=1):
        try:
            check_packet(spec)
        except (AssertionError, IndexError, struct.error, ValueError) as exc:
            fail(number, f"I{slot} does not parse: {exc}")


def main(path: str) -> int:
    with open(path) as handle:
        rows = [line.rstrip("\n") for line in handle if line.strip()]

    for number, row in enumerate(rows, start=1):
        values = dict(field.split("=", 1) for field in row.split("\t"))
        check(number, values)

    if failures:
        print(f"  FAIL  {len(failures)} problem(s) in {len(rows)} profiles")
        for line in failures[:20]:
            print(f"        {line}")
        return 1
    print(f"  ok    {len(rows)} profiles pass the panel validator and parse as their protocols")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1]))
