#!/usr/bin/env python3
"""Draw the donation addresses as QR codes, for the panel's Support page.

Run by hand and commit the result, the same way `lock-deps.sh` is:

    make wallets

A wallet address is the one string in this project that must never be wrong by
a character, so the page that shows it does not hold it. Both the text under
the copy button and the code a phone scans come out of the single table below,
in one pass, and land together in `frontend/src/lib/walletCodes.ts` - which
means the two cannot disagree with each other however either is edited later,
because neither is edited at all. Nothing else in the frontend knows an
address; `lib/wallets.ts` joins these entries to a name and a mark by id, and
an id with no entry here simply does not appear on the page.

The repository README's donation list is filled from the same table in the
same pass, between `wallets:begin`/`wallets:end` markers, so the address a
visitor copies from GitHub and the one the panel shows are one string. The
README gets no QR codes: its fenced blocks give it GitHub's copy button, which
is the same job done the way a web page does it.

Generating at build time rather than serving from the API is deliberate. The
panel's HTTP API is the surface a script automates a VPN server through, and
`tests/test_api_docs.py` holds every route in it to a written description;
"here is where to send money" is not an operation on a server, and adding one
would put it in the OpenAPI document and on the API reference page.

The payload is the bare address, not a `bitcoin:`-style payment URI. Wallets
read both, but a URI is a second string that would have to stay in step with
the one on screen, and a scheme prefix that a particular exchange's scanner
does not know is a deposit that goes nowhere.
"""

import io
import re
import subprocess
from pathlib import Path

import segno

# Error correction M, as apps/accounts/views.py uses for enrolment codes: the
# level every wallet app is tested against, and enough redundancy for a code
# read off a screen at an angle. H would double the size of the Monero symbol
# for a robustness nobody scanning a screen needs.
ERROR_CORRECTION = "m"

OUTPUT = Path(__file__).parent / "frontend/src/lib/walletCodes.ts"
README = Path(__file__).parent.parent / "README.md"

# id -> address. The id is the join key: `frontend/src/lib/wallets.ts` gives
# each one its coin, its chain and the order they are shown in.
WALLETS: dict[str, str] = {
    "btc": "bc1qzx3s920ztkk3njhyl9txq8gxxydg2rl04njm7g",
    "eth": "0x91c814582232cd4dc801a994d63ecbcc37411703",
    "xmr": (
        "85C7MLNzDsMde6dnrZUpA4VerPH8431eYBoMrFL4dgk7SRvdn7YJC"
        "ppZDX2StbpMNeYRqAodnUkwb6k7aPZ43T4vRpWoDA3"
    ),
    "usdt-trc20": "TAWLzQfTKbQmqyZkzG99mBfC1QqNHmndAb",
    "usdt-bep20": "0x91c814582232cd4dc801a994d63ecbcc37411703",
    "sol": "H7qwxBj6WPcnsWAu5vfEqD7DsJ1rvjYgoerNRnfNo9q",
    "trx": "TAWLzQfTKbQmqyZkzG99mBfC1QqNHmndAb",
    "xrp": "rpcvSW6d86UbDMpCLD76VpXn53vbiAeECm",
    "ltc": "ltc1qyj3ppadclkryerwhqyj836eszy05p69ekw40g5",
    "bch": "bitcoincash:qrzghlwlrmq8nrj5hkdwxl968jfy7tgexywffezd48",
}

# id -> (name, detail) for the README's list: what `lib/wallets.ts` shows on
# the Support page, mirrored here the way lib/subnet.sh mirrors awg/subnet.py,
# because the README cannot read TypeScript. Drift here costs a stale label;
# the addresses still come only from the table above.
README_LABELS: dict[str, tuple[str, str]] = {
    "btc": ("Bitcoin", "BTC"),
    "eth": ("Ethereum", "ETH"),
    "xmr": ("Monero", "XMR"),
    "usdt-trc20": ("Tether USD", "USDT · TRC-20 (TRON)"),
    "usdt-bep20": ("Tether USD", "USDT · BEP-20 (BNB Smart Chain)"),
    "sol": ("Solana", "SOL"),
    "trx": ("TRON", "TRX"),
    "xrp": ("XRP", "XRP Ledger"),
    "ltc": ("Litecoin", "LTC"),
    "bch": ("Bitcoin Cash", "BCH"),
}

HEADER = """/*
 * Generated by panel/wallet-codes.py - do not edit. Run `make wallets`.
 *
 * The donation addresses and the QR codes for them, drawn together so they
 * cannot drift apart. Read the script for why they are generated rather than
 * served, and why the payload is the bare address rather than a payment URI.
 *
 * `path` is one stroked path: `stroke-width: 1` down the middle of each row of
 * modules, which is how segno draws a symbol and roughly a third the size of
 * one rectangle per module. Draw it dark on white in both themes - a QR code
 * inverted, or on a tinted card, is the usual reason a camera will not lock
 * on - inside a `viewBox` of `0 0 {size} {size}` with no border of its own:
 * the quiet zone belongs to the padding around it, where it can be white
 * whatever the element behind it is doing.
 */

export interface WalletCode {
  /** Join key. See lib/wallets.ts, which gives it a coin and a chain. */
  readonly id: string;
  /** Exactly what the QR encodes, and exactly what the copy button copies. */
  readonly address: string;
  /** Modules across the symbol, which is also the viewBox this path wants. */
  readonly size: number;
  readonly path: string;
}

export const WALLET_CODES: readonly WalletCode[] = [
"""


def draw(address: str) -> tuple[int, str]:
    """The symbol for one address, as (modules across, SVG path data)."""
    code = segno.make(address, error=ERROR_CORRECTION, micro=False)
    buffer = io.BytesIO()
    # No border: the page pads the code itself, so the quiet zone is white
    # rather than whatever the card is. `unit=""` keeps the viewBox in module
    # units, so the element can be sized in CSS and stay square.
    code.save(buffer, kind="svg", border=0, xmldecl=False, svgns=False, omitsize=True, unit="")
    svg = buffer.getvalue().decode("ascii")
    match = re.search(r'\bd="([^"]+)"', svg)
    if match is None:
        raise SystemExit(f"segno drew a symbol with no path in it: {svg[:200]}")
    return code.symbol_size(border=0)[0], match.group(1)


def readme_block() -> str:
    """The README's address list: one collapsed entry per wallet.

    A fenced block per address, because that is what GitHub puts a copy button
    on - nobody should be selecting an address by hand.
    """
    parts = []
    for wallet_id, address in WALLETS.items():
        labels = README_LABELS.get(wallet_id)
        if labels is None:
            raise SystemExit(f"README_LABELS has no entry for {wallet_id!r}")
        name, detail = labels
        parts.append(
            f"<details>\n"
            f"<summary><b>{name}</b> · {detail}</summary>\n"
            f"\n"
            f"```\n"
            f"{address}\n"
            f"```\n"
            f"\n"
            f"</details>\n"
        )
    return "".join(parts)


def update_readme() -> None:
    text = README.read_text(encoding="utf-8")
    pattern = re.compile(
        r"(<!-- wallets:begin[^\n]*-->\n).*?(^<!-- wallets:end -->)",
        re.DOTALL | re.MULTILINE,
    )
    block = readme_block()
    updated, count = pattern.subn(lambda m: m.group(1) + block + m.group(2), text)
    if count != 1:
        raise SystemExit(
            f"{README} must hold exactly one wallets:begin/wallets:end block, found {count}"
        )
    README.write_text(updated, encoding="utf-8")


def main() -> None:
    lines = [HEADER]
    for wallet_id, address in WALLETS.items():
        size, path = draw(address)
        # Roughly the shape prettier wants. `make wallets` runs it over the
        # result rather than this trying to work out for itself where a
        # 95-character Monero address gets folded.
        lines.append(
            f"  {{\n"
            f'    id: "{wallet_id}",\n'
            f'    address: "{address}",\n'
            f"    size: {size},\n"
            f'    path: "{path}",\n'
            f"  }},\n"
        )
    lines.append("];\n")
    OUTPUT.write_text("".join(lines), encoding="ascii")
    update_readme()

    print(f"wrote {len(WALLETS)} codes to {OUTPUT.relative_to(Path.cwd())}")
    print(f"refreshed the address list in {README.name}")
    # An address typed in wrong is unrecoverable, so say what was drawn and let
    # whoever ran this read it back against wherever the addresses came from.
    for wallet_id, address in WALLETS.items():
        print(f"  {wallet_id:<11} {address}")
    subprocess.run(["git", "diff", "--stat", "--", str(OUTPUT), str(README)], check=False)


if __name__ == "__main__":
    main()
