"""What this API is, written down where a machine can read it.

Everything the panel does, it does through the HTTP API, and until now the only
description of it was `docs/API.md` - prose, in the repository, on a machine
that is not the one being administered. A script author had nothing to point a
tool at: no import into Postman or Insomnia, no client generator, no way to ask
a running panel what it serves.

So the catalog below is the description, and it is rendered as OpenAPI 3.1 by
`document()`. One source, two readers: `GET api/v1/openapi.json` hands the
document to whatever tooling wants it, and the panel's own API page renders the
same document into the reference an admin reads. Neither can drift from the
other, and `tests/test_api_docs.py` walks the URL map to make sure neither can
drift from the routes either - an endpoint added without an entry here fails the
suite.

Three things are deliberately not attempted.

There are no request or response *schemas*, only examples. A schema per body
would be a second declaration of every serializer in the panel, maintained by
hand, and the first one to fall behind would be worse than no schema at all -
a generated client that compiles and is wrong. Examples come off real responses
and are checked by eye against the same fixtures the tests use.

The prose is English, and it stays English. The panel picks its language in the
browser and never tells the server which one, exactly as `awg/validate.py`'s
parameter catalog does; the UI overrides what it has a translation for, keyed by
operation id, and falls back to what is written here.

And nothing here is generated by introspecting the views. DRF can be made to
guess at paths and status codes, and what it produces is a description of the
framework rather than of the panel: no word about which routes an API token may
not touch, which sweeps are one config rewrite rather than thirty, or why a save
that restarts the web service still answers. Those are the things somebody
automating this actually needs, and they have to be written by a person.
"""

from dataclasses import dataclass

# The three ways a request may prove who it is, as the document names them.
#
# "any" is a token or a session, which is nearly everything. "session" is the
# credential surface - see apps.accounts.permissions for why a token is refused
# there - and "none" is the pair of routes that answer before anybody has signed
# in at all.
AUTH_ANY = "any"
AUTH_SESSION = "session"
AUTH_NONE = "none"

BEARER = "bearerAuth"
COOKIE = "sessionAuth"


@dataclass(frozen=True)
class Param:
    """One query or path parameter, as OpenAPI spells it."""

    name: str
    description: str
    where: str = "query"
    required: bool = False
    kind: str = "string"
    default: object | None = None
    values: tuple[str, ...] = ()

    def render(self) -> dict:
        schema: dict = {"type": self.kind}
        if self.values:
            schema["enum"] = list(self.values)
        if self.default is not None:
            schema["default"] = self.default
        return {
            "name": self.name,
            "in": self.where,
            "required": self.required or self.where == "path",
            "description": self.description,
            "schema": schema,
        }


@dataclass(frozen=True)
class Op:
    """One operation: a method, a path, and everything worth knowing about it."""

    id: str
    method: str
    path: str
    tag: str
    summary: str
    description: str
    params: tuple[Param, ...] = ()
    #: Example request body. None means the operation takes none.
    body: object | None = None
    body_note: str = ""
    body_required: bool = True
    #: What the body is sent as. Only `restore` is not JSON, and the difference
    #: is not cosmetic: a reader shown `-d` for a file upload has been shown a
    #: command that cannot work.
    body_type: str = "application/json"
    #: Example success response. None means the operation answers with no body.
    result: object | None = None
    result_note: str = ""
    result_type: str = "application/json"
    success: str = "200"
    #: Failures worth branching on, beyond the ones every route can return.
    codes: tuple[tuple[str, str], ...] = ()
    auth: str = AUTH_ANY

    def security(self) -> list[dict]:
        if self.auth == AUTH_NONE:
            return []
        if self.auth == AUTH_SESSION:
            return [{COOKIE: []}]
        return [{BEARER: []}, {COOKIE: []}]

    def render(self) -> dict:
        out: dict = {
            "operationId": self.id,
            "tags": [self.tag],
            "summary": self.summary,
            "description": self.description,
            "security": self.security(),
            "responses": self._responses(),
        }
        if self.params:
            out["parameters"] = [param.render() for param in self.params]
        if self.body is not None:
            out["requestBody"] = {
                "required": self.body_required,
                "content": {self.body_type: {"schema": self._body_schema(), "example": self.body}},
            }
            if self.body_note:
                out["requestBody"]["description"] = self.body_note
        return out

    def _body_schema(self) -> dict:
        """An object, unless the body is a file - which a generator has to know."""
        if self.body_type == "multipart/form-data":
            return {
                "type": "object",
                "properties": {"file": {"type": "string", "format": "binary"}},
                "required": ["file"],
            }
        return {"type": "object"}

    def _responses(self) -> dict:
        ok: dict = {"description": self.result_note or _SUCCESS_WORDS.get(self.success, "Success.")}
        if self.result is not None:
            schema = (
                {"type": "string"} if self.result_type.startswith("text/") else {"type": "object"}
            )
            if self.result_type in {"image/png", "application/zip", "application/gzip"}:
                schema = {"type": "string", "format": "binary"}
            content: dict = {"schema": schema}
            # A binary body has no example worth printing; the description says
            # what it is instead.
            if schema.get("format") != "binary":
                content["example"] = self.result
            ok["content"] = {self.result_type: content}
        out = {self.success: ok}
        for code, note in self.codes:
            out[code] = {"description": note}
        return out


_SUCCESS_WORDS = {
    "200": "The current state.",
    "201": "Created.",
    "204": "Done. No body.",
}


# --------------------------------------------------------------------------
# Groups
# --------------------------------------------------------------------------

TAGS: tuple[tuple[str, str], ...] = (
    (
        "Auth",
        "Signing in, and finding out who the caller is. A script normally skips all "
        "of this and sends a bearer token instead.",
    ),
    (
        "Clients",
        "The peers on the tunnel: creating them, handing out their configurations, "
        "reading what they have used, and taking them away. This is the half of the "
        "API most automation only ever touches.",
    ),
    (
        "Server",
        "The interface itself - its address pool, its port, and the obfuscation "
        "parameters both ends have to agree on. Changing some of these restarts the "
        "tunnel; each operation says which.",
    ),
    (
        "Stats",
        "What is moving now and what has moved since. Read from files the collector "
        "writes, so polling these is cheap.",
    ),
    (
        "Events and logs",
        "Two records, kept apart because they are made of different things: the "
        "panel's own ledger of what was done, and a window on journald.",
    ),
    (
        "Panel",
        "The panel rather than the tunnel: its settings, its certificate, its backup "
        "archive and its version.",
    ),
    (
        "Credentials",
        "The password, the second factor, the signed-in browsers and the tokens. "
        "Every route here refuses an API token, whatever it is asking for - see the "
        "note on the Authentication tab.",
    ),
    (
        "System",
        "Two routes that describe the panel rather than anything it manages.",
    ),
)


# --------------------------------------------------------------------------
# The catalog
# --------------------------------------------------------------------------

_CLIENT_ROW = {
    "name": "phone",
    "publicKey": "hE1v...=",
    "ip": "10.13.13.2",
    "ip6": "fd7a:1e5f:22::2",
    "allowedIps": "0.0.0.0/0, ::/0",
    "leaksIpv6": False,
    "enabled": True,
    "disabledReason": "",
    "createdAt": "2026-08-04T18:00:00Z",
    "expiresAt": None,
    "expiryOverridden": False,
    "quotaBytes": 0,
    "downBps": 0,
    "upBps": 0,
    "email": "",
    "note": "",
    "status": "online",
    "online": True,
    "lastHandshake": 1754332800,
    "lastSeen": 1754332799,
    "endpoint": "203.0.113.9:51234",
    "rxBytes": 8123456,
    "txBytes": 91234567,
    "offsetRx": 0,
    "offsetTx": 0,
    "rateRx": 1024,
    "rateTx": 40960,
    "quotaUsed": 99358023,
    "quotaPercent": 0,
}

_TOKEN_ROW = {
    "id": "9f1c6b2a-2d4e-4d7f-8a1b-3c5e7f9a0b2d",
    "name": "nightly backup",
    "hint": "x7Qa",
    "createdAt": "2026-08-05T09:14:02Z",
    "expiresAt": "2026-09-04T09:14:02Z",
    "expiresIn": 2592000,
    "renewOnUse": True,
    "lastUsedAt": "2026-08-17T03:00:11Z",
    "lastUsedIp": "203.0.113.10",
    "expired": False,
}

_TRAFFIC_SERIES = {
    "daily": [{"period": "2026-08-13", "rx": 3142857142, "tx": 22000000000}],
    "monthly": [{"period": "2026-08", "rx": 41000000000, "tx": 310000000000}],
    "earliest": "2025-11-04",
}

_WINDOW_PARAMS = (
    Param(
        "from",
        "First day of the window, YYYY-MM-DD. Left out, the answer runs back as far as it reaches.",
    ),
    Param(
        "to",
        "Last day of the window, YYYY-MM-DD. Left out, it runs to today. A window "
        "past today stops at today.",
    ),
)


CATALOG: tuple[Op, ...] = (
    # ---------------------------------------------------------------- auth
    Op(
        id="login",
        method="post",
        path="auth/login",
        tag="Auth",
        summary="Sign in and receive a session cookie",
        description=(
            "Omit `totp` on the first attempt. An account with a confirmed "
            'authenticator answers 401 with `detail: "totp_required"`; repeat the '
            "request with the code. Repeated failures lock the source address out "
            "for 15 minutes.\n\n"
            "A script should not be doing this. A bearer token needs no cookie jar, "
            "no CSRF token and no second factor, and it can be revoked on its own "
            "without changing the password."
        ),
        body={"username": "admin", "password": "...", "totp": "123456"},
        result={
            "authenticated": True,
            "username": "admin",
            "otpRequired": False,
            "version": "1.0.0",
            "theme": "system",
            "language": "en",
            "basePath": "/awg/k2p9x4mt7wq1bz8n5rv3/",
            "mock": False,
        },
        codes=(
            ("401", "Wrong credentials, or `totp_required` for an account with a second factor."),
            ("403", "Locked out after repeated failures; `detail` says for how long."),
        ),
        auth=AUTH_NONE,
    ),
    Op(
        id="logout",
        method="post",
        path="auth/logout",
        tag="Auth",
        summary="End this browser's session",
        description=(
            "Refused to a token for want of anything to do: there is no session "
            "behind one to end. A script that wants its credential to stop working "
            "revokes the token."
        ),
        success="204",
        auth=AUTH_SESSION,
    ),
    Op(
        id="session",
        method="get",
        path="auth/session",
        tag="Auth",
        summary="Who the caller is, and what the panel is",
        description=(
            "The one route besides `health` that answers to nobody in particular: it "
            "is how the login page learns the panel's name and how a browser is given "
            "its CSRF cookie.\n\n"
            "For a request carrying a bearer token the answer also has a `token` "
            "object naming the credential in use and when it runs out. That is the "
            "route a script uses to check its own token before a long job - the "
            "token list itself is closed to tokens, and a credential that fails "
            "silently on a Tuesday is the thing this saves you from."
        ),
        result={
            "authenticated": True,
            "username": "admin",
            "otpRequired": False,
            "version": "1.0.0",
            "theme": "system",
            "language": "en",
            "basePath": "/awg/k2p9x4mt7wq1bz8n5rv3/",
            "mock": False,
            "token": {
                "name": "nightly backup",
                "expiresAt": "2026-09-04T09:14:02Z",
                "renewOnUse": True,
            },
        },
        auth=AUTH_NONE,
    ),
    # ------------------------------------------------------------- clients
    Op(
        id="clientList",
        method="get",
        path="clients",
        tag="Clients",
        summary="One page of clients, with counts over the whole server",
        description=(
            "`clients` holds at most `pageSize` rows; every count beside it is over "
            "the whole server, because none of them is answerable from a page. "
            "`total` is what the search and the filter matched, `totalAll` is how "
            "many clients there are, and the last three are what a bulk removal "
            "would take - so a sweep can be sized before it is run.\n\n"
            "`rxBytes` is what the client **uploaded** and `txBytes` what it "
            "**downloaded**: the server's point of view, matching `awg show dump`. "
            "Both survive interface restarts.\n\n"
            "A parameter this version does not understand is ignored rather than "
            "rejected, so an old bookmark opens the list instead of a 400. Rows carry "
            "no `dns` - fetch a client by name for that."
        ),
        params=(
            Param(
                "q",
                "Substring, case-insensitive, over name, address, note, email and endpoint.",
            ),
            Param(
                "status",
                "Narrow by state. `expired` reads the date, which a client can answer "
                "yes to while it is online.",
                default="all",
                values=("all", "active", "online", "offline", "disabled", "expired"),
            ),
            Param(
                "sort",
                "Ordering, applied to every client before the page is cut.",
                default="created",
                values=("created", "name", "ip", "usage", "lastHandshake"),
            ),
            Param(
                "direction", "Which way that ordering runs.", default="asc", values=("asc", "desc")
            ),
            Param(
                "page",
                "1-based. A page past the end answers the last page that has rows, and says so.",
                kind="integer",
                default=1,
            ),
            Param(
                "pageSize",
                "Capped at 500. `0` means every row the query selected, unpaged - the "
                "one request whose cost follows the size of the server.",
                kind="integer",
                default=50,
            ),
        ),
        result={
            "clients": [_CLIENT_ROW],
            "subnetCidr": "10.13.13.0/24",
            "freeIps": 251,
            "total": 1,
            "totalAll": 1,
            "expiredCount": 0,
            "disabledCount": 0,
            "expiredOrDisabledCount": 0,
            "page": 1,
            "pageSize": 50,
        },
        codes=(("503", '`code: "not_configured"` - there is no server configuration here.'),),
    ),
    Op(
        id="clientCreate",
        method="post",
        path="clients",
        tag="Clients",
        summary="Add a client",
        description=(
            "Nothing is required; every field falls back to `clients.env`. Names match "
            "`^[A-Za-z0-9][A-Za-z0-9._-]{0,31}$`.\n\n"
            "`name` left out - or sent blank - has the server draw one: nine characters of "
            "lower-case letters and digits, without `l`, `1`, `o` and `0`. It is checked "
            "under the config lock against the peers in the config and the files under "
            "`clients/`, so a drawn name lands on nothing that already exists, and the "
            "created client comes back carrying whichever name it ended up with.\n\n"
            "The address is the lowest free host in the subnet, gaps reused, and the "
            "peer is applied to the running interface with `awg syncconf`, so no "
            "existing session drops. The answer is the created client, private key "
            "excluded - fetch its config for that."
        ),
        body={
            "name": "laptop",
            "allowedIps": "0.0.0.0/0",
            "dns": "1.1.1.1",
            "quotaBytes": 53687091200,
            "expiresAt": "2026-12-31T23:59:59Z",
            "downBps": 50000000,
            "upBps": 0,
            "email": "",
            "note": "",
        },
        result=_CLIENT_ROW,
        success="201",
        codes=(
            ("409", '`code: "name_in_use"` for a name that is taken; without it, a full pool.'),
        ),
    ),
    Op(
        id="clientGet",
        method="get",
        path="clients/{name}",
        tag="Clients",
        summary="One client, with its DNS line",
        description=(
            "The same shape as a list row plus `dns`, found across every client on "
            "the server rather than within a page.\n\n"
            "`dns` is the line in the client's own config file - what the device is "
            'holding. **Absent and `""` are different answers**: absent is a list '
            'row, which was never asked, and `""` is a config with no `DNS` line at '
            "all."
        ),
        params=(Param("name", "The client's name, as the config file spells it.", where="path"),),
        result=dict(_CLIENT_ROW, dns="8.8.8.8, 8.8.4.4"),
        codes=(("404", "No client of that name."),),
    ),
    Op(
        id="clientUpdate",
        method="put",
        path="clients/{name}",
        tag="Clients",
        summary="Change a client, or switch it off",
        description=(
            "Any subset of the fields. Renaming keeps the keys and the address, so "
            "nothing has to be re-imported.\n\n"
            "`enabled: false` writes the shared `# Disabled` marker and takes the key "
            "off the kernel; the address stays reserved and the config file is kept. "
            "Switching a lapsed client back on records that an admin overruled its "
            "date - `expiryOverridden` comes back true, the collector stops enforcing "
            "the expiry, and `remove-expired` skips it. Changing or clearing "
            "`expiresAt` ends that.\n\n"
            "Speed limits are bits per second, `0` for none, and are refused rather "
            "than stored where nothing would enforce them: with shaping off, with "
            "`upBps` on a server that does not shape uploads, or on a tunnel subnet "
            "of `/16` or wider."
        ),
        params=(Param("name", "The client to change.", where="path"),),
        body={"note": "work laptop", "quotaBytes": 107374182400, "enabled": True},
        body_note="Send only what changes. Anything left out is left alone.",
        result=_CLIENT_ROW,
        codes=(
            ("400", "A field was rejected; `errors` names it."),
            ("404", "No client of that name."),
            ("409", '`code: "name_in_use"`: the new name is taken.'),
        ),
    ),
    Op(
        id="clientDelete",
        method="delete",
        path="clients/{name}",
        tag="Clients",
        summary="Remove a client",
        description=(
            "Takes the peer, its config file, its metadata and its traffic row, and "
            "applies live. Its speed limit goes with it, which matters: the shaping "
            "structure is keyed by tunnel address and addresses are reused, so a "
            "limit left behind would be inherited by whoever gets that address next."
        ),
        params=(Param("name", "The client to remove.", where="path"),),
        success="204",
        codes=(("404", "No client of that name."),),
    ),
    Op(
        id="clientConfig",
        method="get",
        path="clients/{name}/config",
        tag="Clients",
        summary="Download a client configuration",
        description=(
            "`text/plain`, as an attachment. **It contains the client's private "
            "key.**\n\n"
            "The file on disk is served verbatim except for one substitution: with "
            "`configEndpointMode` set to `domain`, the host in the `Endpoint` line "
            "becomes the panel's certificate domain. Nothing is written back."
        ),
        params=(Param("name", "The client whose configuration to fetch.", where="path"),),
        result=(
            "[Interface]\nPrivateKey = ...\nAddress = 10.13.13.2/24\nDNS = 8.8.8.8\n\n"
            "[Peer]\nPublicKey = Xq3...=\nEndpoint = 203.0.113.7:41820\n"
        ),
        result_type="text/plain",
        codes=(("404", "No client of that name."),),
    ),
    Op(
        id="clientQr",
        method="get",
        path="clients/{name}/qr",
        tag="Clients",
        summary="The same configuration as a QR code",
        description=(
            "`image/png`, `Cache-Control: no-store`, same endpoint substitution as the "
            "download. It encodes the private key, so treat the image as the secret it is."
        ),
        params=(Param("name", "The client to draw.", where="path"),),
        result="<png>",
        result_type="image/png",
        result_note="A PNG of the client's configuration.",
        codes=(("404", "No client of that name."),),
    ),
    Op(
        id="clientTraffic",
        method="get",
        path="clients/{name}/traffic",
        tag="Clients",
        summary="One client's traffic, by day and by month",
        description=(
            "The same shape as the server's own history. Its window stops where "
            "retention does: per-client rows are swept after 400 days, and the monthly "
            "series starts at the first whole month inside them, because a month half "
            "of which has been pruned is a short bar for a reason that is not traffic.\n\n"
            "It can legitimately come out under the client's all-time totals - a "
            "client older than the window has moved more than its history can account for."
        ),
        params=(Param("name", "The client to report on.", where="path"), *_WINDOW_PARAMS),
        result=_TRAFFIC_SERIES,
        codes=(("404", "No client of that name."),),
    ),
    Op(
        id="clientResetKeys",
        method="post",
        path="clients/{name}/reset-keys",
        tag="Clients",
        summary="Issue a new keypair for a client",
        description=(
            "New private, public and preshared keys; the name, the address and every "
            "option are kept. The old configuration stops working immediately, so the "
            "device has to re-import before it connects again."
        ),
        params=(Param("name", "The client to re-key.", where="path"),),
        body=None,
        result=_CLIENT_ROW,
        codes=(("404", "No client of that name."),),
    ),
    Op(
        id="clientResetUsage",
        method="post",
        path="clients/{name}/reset-usage",
        tag="Clients",
        summary="Clear what a client has used",
        description=(
            "Both figures: the all-time totals and the stored history. The totals are "
            "zeroed with an offset, so `traffic.db` keeps the true number; the history "
            "rows are deleted outright.\n\n"
            "The collector holds today's figure in memory in another process, so today's "
            "bar can reappear until its next reconcile - within one `enforceIntervalSec`."
        ),
        params=(Param("name", "The client to clear.", where="path"),),
        body=None,
        result=_CLIENT_ROW,
        codes=(("404", "No client of that name."),),
    ),
    Op(
        id="clientBulkRemove",
        method="post",
        path="clients/bulk-remove",
        tag="Clients",
        summary="Remove every expired or disabled client at once",
        description=(
            "Worth using rather than a loop: every client in the sweep leaves in a "
            "single config rewrite and a single `awg syncconf`, where thirty deletions "
            "are thirty of each and thirty windows in which the config on disk is "
            "halfway through the job.\n\n"
            "`expired` takes every client whose date has passed, except one an admin "
            "switched back on. `disabled` takes every client that is not working, "
            "including one still switched on and already over its quota. Both together "
            "is a union, not two passes.\n\n"
            "Both default to false, and a body naming neither is a 400 rather than a "
            'removal of nothing: "remove nothing" and "my flag never arrived" are '
            "different mistakes."
        ),
        body={"expired": True, "disabled": True},
        result={"removed": ["old-phone", "laptop"], "count": 2},
        codes=(("400", "Neither flag was set."),),
    ),
    Op(
        id="clientRemoveExpired",
        method="post",
        path="clients/remove-expired",
        tag="Clients",
        summary="Remove only the expired clients",
        description=(
            "The `expired` half of the sweep above, which is what it did before "
            "`bulk-remove` existed. Takes no body and answers in the same shape."
        ),
        body=None,
        result={"removed": ["old-phone"], "count": 1},
    ),
    Op(
        id="clientBulkLimit",
        method="post",
        path="clients/bulk-limit",
        tag="Clients",
        summary="Write one speed limit over every client",
        description=(
            "The operation the per-client form cannot express: an admin who has decided "
            "everybody gets 20 Mbit should not have to open four thousand dialogs.\n\n"
            "It overwrites and there is no undo. Both fields are required rather than "
            "defaulted for that reason - a body that lost half of itself in transit must "
            'not read as "and clear everybody\'s upload limit while you are here".\n\n'
            "`changed` counts the rows that actually moved, so calling it twice with the "
            "same numbers answers 0. `applied: false` with a `reason` means the numbers "
            "were stored but the kernel could not be brought into line; the collector "
            "applies them when it can."
        ),
        body={"downBps": 20000000, "upBps": 0},
        result={"changed": 4093, "applied": True, "reason": ""},
        codes=(("400", "Shaping is off, or a field is not acceptable on this server."),),
    ),
    Op(
        id="clientExport",
        method="get",
        path="clients/export.zip",
        tag="Clients",
        summary="Every client configuration in one archive",
        description=(
            "`application/zip`, with the same endpoint substitution as a single "
            "download. **It contains every client's private key.**"
        ),
        result="<zip>",
        result_type="application/zip",
        result_note="A zip archive of every client's .conf file.",
    ),
    # -------------------------------------------------------------- server
    Op(
        id="serverGet",
        method="get",
        path="server",
        tag="Server",
        summary="The interface as it is configured",
        description=(
            "The server's private key is never included.\n\n"
            '`subnet6Cidr` and `subnet6Mode` are read-only and both `""` on a server '
            "with no IPv6. Which mode applies follows from what the machine actually "
            "has, which the installer works out."
        ),
        result={
            "iface": "awg0",
            "address": "10.13.13.1/24, fd7a:1e5f:22::1/64",
            "subnetCidr": "10.13.13.0/24",
            "subnetCapacity": 253,
            "subnet6Cidr": "fd7a:1e5f:22::/64",
            "subnet6Mode": "native",
            "listenPort": 41820,
            "mtu": 1400,
            "publicKey": "Xq3...=",
            "dns": "8.8.8.8, 8.8.4.4",
            "endpointHost": "203.0.113.7",
            "endpointPort": "",
            "allowedIpsDefault": "0.0.0.0/0",
            "keepalive": "25",
            "params": {"Jc": "5", "Jmin": "63", "S1": "199"},
            "postUp": ["iptables -t nat -A POSTROUTING ..."],
            "postDown": ["..."],
            "preDown": ["/usr/local/bin/awg-panel manage trafficsync || true"],
        },
        codes=(("503", '`code: "not_configured"` - there is no server configuration here.'),),
    ),
    Op(
        id="serverUpdate",
        method="put",
        path="server",
        tag="Server",
        summary="Change the interface",
        description=(
            "Send only what changed - any network field, or any key in `params`.\n\n"
            "**The save performs the restart.** `needsRestart` is what the change cost, "
            "not a job left for the caller: a changed port, address, MTU or obfuscation "
            "parameter takes the interface down and back up before the response is "
            "written, so every session drops for a second or two. `applied` is false "
            "only when it could not be done, with a sentence in `warnings` saying which.\n\n"
            "`mustReimport` means the client configs on disk have already been "
            "regenerated and the devices now need the new file; `clients/export.zip` is "
            "how to collect them. Hook changes are written but not applied, because they "
            "only run at the next bring-up.\n\n"
            "A `listenPort` that another process already holds is saved and warned about "
            "by name, not refused: a port a filtered network leaves open is a deliberate "
            "choice, and the warning is the only place the process in the way is named."
        ),
        body={"listenPort": 51820, "params": {"S1": "148", "Jc": "4"}},
        body_note="Any subset of the fields `GET server` returns.",
        result={
            "needsRestart": True,
            "mustReimport": True,
            "applied": True,
            "warnings": ["DisableCookies is on: this server no longer answers a flood ..."],
        },
        codes=(
            ("400", "A parameter was rejected; `errors` carries a message per field."),
            ("502", "`awg-quick` failed; `detail` summarises its stderr."),
        ),
    ),
    Op(
        id="serverParams",
        method="get",
        path="server/params",
        tag="Server",
        summary="The parameter catalog",
        description=(
            "The single source of truth for the validation rules *and* the help text "
            "the UI renders, so the two cannot drift. `mustMatchClient` means changing "
            "it invalidates every issued config; `importerSafe: false` means the setting "
            "arrived in AmneziaWG 3.0 (3.1 for `RandomTrailers`) and the Amnezia mobile "
            "app silently discards it on import; `supported: false` means the installed "
            "module or tools cannot do it.\n\n"
            "`recommended` names a *band* rather than a value for the obfuscation groups: "
            "a value this project recommended to everybody would be one every server "
            "shared, and a shared value is a signature."
        ),
        result=[
            {
                "key": "S1",
                "group": "sizes",
                "label": "Init packet padding",
                "kind": "int",
                "helpShort": "Random bytes added in front of the handshake initiation packet.",
                "helpLong": "WireGuard's handshake packets have fixed, well-known sizes ...",
                "mustMatchClient": True,
                "importerSafe": True,
                "supported": True,
                "min": 0,
                "max": 1280,
                "recommended": "24-320, drawn per server",
                "optional": True,
            }
        ],
    ),
    Op(
        id="serverReconfigure",
        method="post",
        path="server/reconfigure",
        tag="Server",
        summary="Draw a fresh obfuscation set as a preview",
        description=(
            "Draws a complete, valid set for this server alone and returns it. **Nothing "
            "is saved** until you `PUT server` with it.\n\n"
            "One draw covers the whole Obfuscation page: `Jc`-`I5` and the AmneziaWG 3.0 "
            "group behind them. The profile names a band in each of the two preset "
            "tables - the obfuscation bands trade bandwidth for cover, the advanced ones "
            "trade how often the server handshakes at all.\n\n"
            "Every profile draws every value at random; they differ in the band, which is "
            "the trade between how much of the protocol's shape a value hides and what "
            "sending it costs. `random` spans the other three, so the choice of profile is "
            "not itself something to fingerprint a server by.\n\n"
            "An empty value is meaningful, not missing: it is how `PUT server` spells "
            '"remove this line". That covers an unused `I` slot and `RandomTrailers`, '
            "which is left off because it needs AmneziaWG 3.1 rather than 3.0. Send the "
            "whole `params` object back unchanged."
        ),
        body={"profile": "standard"},
        body_required=False,
        body_note="Optional. `profile` is standard, dpi, fast or random; `{}` means standard.",
        result={
            "params": {
                "Jc": "4",
                "Jmin": "44",
                "Jmax": "185",
                "S1": "48",
                "H1": "1190147702-1504725727",
                "I1": "<b 0x000100082112a442><r 12>",
                "I4": "",
                "HeaderProtectionKey": "xYbOANvXjB9HdbfeC92cefXNNd8U2iIXtvmnHMogkCs=",
                "ContentPaddingAddition": "12-64",
                "RekeyAfterTime": "163",
                "RandomTrailers": "",
            },
            "warnings": [],
        },
        codes=(("400", "An unknown profile."),),
    ),
    Op(
        id="serverRestart",
        method="post",
        path="server/restart",
        tag="Server",
        summary="Take the tunnel down and bring it back",
        description=(
            "`awg-quick down && up`. Every session drops for a moment. A save that needs "
            "a restart already does this, so this is for the cases it could not: an "
            "interface that was down at the time, a restart that failed, or a hook change."
        ),
        body=None,
        success="204",
        codes=(("502", "`awg-quick` failed; `detail` summarises its stderr."),),
    ),
    Op(
        id="serverStop",
        method="post",
        path="server/stop",
        tag="Server",
        summary="Take the tunnel down and leave it down",
        description=(
            "`systemctl stop awg-quick@<iface>` where systemd believes it is holding "
            "the interface up, and `awg-quick down` if the interface is still there "
            "afterwards. The unit is Type=oneshot with RemainAfterExit=yes and the "
            "installer brings the tunnel up with awg-quick, so a stop that trusted "
            "systemd alone would exit 0 over a tunnel with every client still on "
            "it.\n\n"
            "Every session drops and none come back until `server/start`.\n\n"
            "The unit is left enabled, so a reboot brings the tunnel up again. A stop "
            "that outlived a reboot would be a second piece of state with nothing in "
            "`server/status` to show it; use `systemctl disable` for that.\n\n"
            "Idempotent: stopping a tunnel that is already down answers 204."
        ),
        body=None,
        success="204",
        codes=(("502", "The stop failed; `detail` carries what the unit logged."),),
    ),
    Op(
        id="serverStart",
        method="post",
        path="server/start",
        tag="Server",
        summary="Bring the tunnel back up",
        description=(
            "`systemctl start awg-quick@<iface>` where the unit exists - systemd runs "
            "ExecStop only for a unit it started, so this is what makes the next stop "
            "work - and `awg-quick up` otherwise. Then a `syncconf` so the interface "
            "comes back without the clients quota, expiry or an admin had switched "
            "off - a bring-up loads the whole config, disabled peers included.\n\n"
            "Idempotent: starting a tunnel that is already up answers 204."
        ),
        body=None,
        success="204",
        codes=(("502", "The start failed; `detail` carries what the unit logged."),),
    ),
    Op(
        id="serverStatus",
        method="get",
        path="server/status",
        tag="Server",
        summary="Is the tunnel up, and what can this build do",
        description=(
            "Answers 200 even on a server with no configuration at all, because this is "
            "the route somebody uses to find out what is wrong.\n\n"
            "`moduleVersion` is the module the kernel is **running**, not what `modinfo` "
            "reports about the file on disk. When the two differ - an upgrade that could "
            "not unload the module in use - `warnings` carries a sentence naming both."
        ),
        result={
            "ifaceUp": True,
            "moduleLoaded": True,
            "toolsVersion": "amneziawg-tools v3.1.20260812 - https://amnezia.org",
            "moduleVersion": "3.1.20260812",
            "features": {
                "headerRanges": True,
                "imitationPackets": True,
                "headerProtectionKey": True,
                "contentPadding": True,
                "timers": True,
                "randomTrailers": True,
            },
            "serviceActive": "active",
            "serviceEnabled": "enabled",
            "listening": True,
            "warnings": [],
        },
    ),
    # --------------------------------------------------------------- stats
    Op(
        id="statsLive",
        method="get",
        path="stats/live",
        tag="Stats",
        summary="The collector's blob: rates, peers and what the machine is spending",
        description=(
            "This route never shells out to `awg` - it reads a file the collector wrote - "
            "so polling it every two seconds costs nothing. If the collector is not "
            "running the blob goes stale; check `ts`.\n\n"
            "`?peers=` is what keeps the answer the size of a screen rather than the size "
            "of the server. Absent means every peer; present and empty means none of them, "
            "which is what a dashboard reading only the totals should send; present with "
            "keys means those. At most 150 keys are honoured - beyond that the request "
            "line itself would be refused by the web server.\n\n"
            "`confStamp` is observed as the request is answered and changes whenever the "
            "server configuration is rewritten - by this API, by `awg-panel manage`, or by "
            "the collector enforcing a limit. It is **opaque**: compare it with the last "
            "one seen and do not parse it. Watching it is how a caller learns that a "
            "client list it is holding has gone stale, without polling that list."
        ),
        params=(
            Param(
                "peers",
                "Comma-separated public keys to report on. Percent-encode them: a key "
                "contains + / and =.",
            ),
        ),
        result={
            "ts": 1754332800,
            "ifaceUp": True,
            "ifaceSince": 1754246400,
            "ifaceIndex": 12,
            "online": 2,
            "total": 5,
            "totalRateRx": 2048,
            "totalRateTx": 81920,
            "peers": {
                "hE1v...=": {
                    "rateRx": 1024,
                    "rateTx": 40960,
                    "rx": 8123456,
                    "tx": 91234567,
                    "handshake": 1754332788,
                    "lastRx": 1754332799,
                    "status": "online",
                    "endpoint": "203.0.113.9:51234",
                    "online": True,
                }
            },
            "system": {
                "cpu": 3.4,
                "memUsed": 812,
                "memTotal": 3936,
                "swapUsed": 134217728,
                "swapTotal": 1073741824,
                "uptime": 98123,
                "load": [0.1, 0.2, 0.3],
                "diskUsed": 8589934592,
                "diskFree": 30064771072,
                "diskTotal": 41072328704,
            },
            "confStamp": "1a2b3c4d5e-4f1-2c9",
        },
    ),
    Op(
        id="statsSummary",
        method="get",
        path="stats/summary",
        tag="Stats",
        summary="Totals, online count and today's traffic",
        description=(
            "`todayRx`/`todayTx` are bytes since **UTC** midnight, written every ten "
            "seconds, and are not affected by a client being deleted: bytes that moved "
            "today moved today. `totalRx`/`totalTx` are all-time over the clients that "
            "still exist, so deleting one does take its figure with it."
        ),
        result={
            "totalClients": 5,
            "onlineClients": 2,
            "disabledClients": 1,
            "todayRx": 3142857142,
            "todayTx": 22000000000,
            "totalRx": 41000000000,
            "totalTx": 310000000000,
            "uptime": 98123,
            "ifaceUp": True,
        },
    ),
    Op(
        id="statsTraffic",
        method="get",
        path="stats/traffic",
        tag="Stats",
        summary="What the whole server has carried, by day and by month",
        description=(
            "Left alone, `daily` is the last 90 days and `monthly` the last 36 months, "
            "both oldest first. `earliest` is the first day there is a row for, and "
            "neither series starts before it - three years back is a real date on a "
            "server installed last month.\n\n"
            "Both series are cut to `from`/`to`, so one range control can drive both "
            "views. Every period in the window is present, including the ones nothing "
            "moved on. `period` is a label rather than a timestamp: converting a month "
            "into a local zone would relabel August as July west of Greenwich."
        ),
        params=_WINDOW_PARAMS,
        result=_TRAFFIC_SERIES,
        codes=(("400", "A date that is not one, or a `from` later than its `to`."),),
    ),
    Op(
        id="statsTrafficReset",
        method="post",
        path="stats/traffic/reset",
        tag="Stats",
        summary="Clear every traffic figure on the server",
        description=(
            "The server-wide sibling of `reset-usage`, and it takes the one thing that "
            "endpoint leaves alone: the server's own days. Every client's all-time "
            "totals, every client's stored days and months, and the whole of "
            "`stats/traffic` go to zero at once.\n\n"
            "Nothing about the clients themselves is touched - no key, address, quota, "
            "expiry or configuration - and nothing disconnects. A client switched off "
            "for its quota is switched back on by the collector's next enforcement "
            "pass, which finds nothing left to enforce.\n\n"
            "It is finished in two places. This call stores an offset against every "
            "client and empties the tables, which is enough for every figure the API "
            "reports; the collector then subtracts those offsets out of `traffic.db` "
            "itself on its next flush, within ten seconds. Both halves read as zero "
            "throughout, so there is no window in which a caller sees the old numbers "
            "come back - and bytes that move in between are counted, because they "
            "moved after the wipe.\n\n"
            "`clients` counts the clients that had anything to clear, not every client "
            "on the server. `serverDays` and `clientDays` are the stored rows this call "
            "deleted; the collector may take a handful more of each when it folds - the "
            "rows it wrote back in the meantime - and those are not in these numbers.\n\n"
            "**There is no undo, and no copy is kept anywhere.** A `panel.traffic-cleared` "
            "row in the activity log is the only record that the figures were ever "
            "anything else."
        ),
        body=None,
        result={"clients": 12, "serverDays": 274, "clientDays": 3901},
    ),
    # ------------------------------------------------------- events + logs
    Op(
        id="events",
        method="get",
        path="events",
        tag="Events and logs",
        summary="The panel's own ledger of what was done",
        description=(
            "Newest first. `kind` is `<category>.<what-happened>` and is the whole of "
            "what an event means: no sentence is stored, because a sentence written on "
            "the server is a sentence in one language. A reader should show a kind it "
            "does not recognise as its own name rather than dropping the row.\n\n"
            "`actor` is the account that did it, **empty for anything the panel decided "
            "on its own** - a client switched off for its quota was switched off by "
            "nobody. For a request authenticated by a token it is `api:` followed by the "
            "token's name, which is what makes naming a token worth doing.\n\n"
            "`detail` is the named values a reader builds its sentence from, and what is "
            "in it depends on the kind: the fields a client edit moved, the window a token "
            "was given, which attempt a refused sign-in was. A settings save carries `keys` "
            "for everything that changed and `values` as `key=value` for the settings whose "
            "value says nothing about how to reach this panel - so the secret path is "
            "recorded as having changed and never as what it changed to.\n\n"
            "A bulk operation is one row with a count, not one per client. Rows are swept "
            "after 180 days, with a 20 000-row ceiling behind that."
        ),
        params=(
            Param(
                "category",
                "The half of `kind` in front of the dot.",
                values=("client", "server", "panel", "auth"),
            ),
            Param("severity", "How loud the row is.", values=("info", "warning")),
            Param("q", "Substring of the actor or the target."),
            Param("page", "1-based.", kind="integer", default=1),
            Param("pageSize", "1-200.", kind="integer", default=25),
        ),
        result={
            "events": [
                {
                    "id": 412,
                    "at": "2026-08-16T09:14:02Z",
                    "kind": "client.quota-reached",
                    "severity": "warning",
                    "actor": "",
                    "actorIp": "",
                    "target": "phone",
                    "detail": {},
                },
                {
                    "id": 411,
                    "at": "2026-08-16T09:02:55Z",
                    "kind": "client.updated",
                    "severity": "info",
                    "actor": "api:nightly backup",
                    "actorIp": "203.0.113.10",
                    "target": "phone",
                    "detail": {"fields": ["quotaBytes"]},
                },
                {
                    "id": 410,
                    "at": "2026-08-16T08:51:30Z",
                    "kind": "panel.settings-saved",
                    "severity": "info",
                    "actor": "admin",
                    "actorIp": "203.0.113.10",
                    "target": "",
                    "detail": {
                        "count": 2,
                        "keys": ["shaperOn", "webBasePath"],
                        "values": ["shaperOn=0"],
                    },
                },
            ],
            "total": 412,
            "page": 1,
            "pageSize": 25,
        },
    ),
    Op(
        id="eventsClear",
        method="delete",
        path="events",
        tag="Events and logs",
        summary="Empty the activity log",
        description=(
            "Every row, not the ones a `category` or a `q` would select - the query "
            "string is ignored here. Emptying the log is one act with one meaning, and "
            "a clear whose effect depended on a filter three fields away would be the "
            "one operation in the panel that does something different to the operator "
            "who was searching it.\n\n"
            "One row is written straight afterwards, `panel.events-cleared`, carrying "
            "the count and the account that did it. A cleared log is therefore a log "
            "with one line in it rather than a blank one, which is the difference "
            "between tidying up and an audit trail that can be made to have never "
            "existed - and it is the row the next clear takes.\n\n"
            "**Sign-in only.** A token that could empty this could erase what it had "
            "done; see `Credentials` for the same line drawn one step earlier.\n\n"
            "Nothing else goes with it: the journal belongs to journald, and the "
            "traffic history is measurements rather than a ledger."
        ),
        result={"removed": 412},
        codes=(("403", "An API token asked."),),
        auth=AUTH_SESSION,
    ),
    Op(
        id="logs",
        method="get",
        path="logs",
        tag="Events and logs",
        summary="The last lines one service wrote to the journal",
        description=(
            "**Oldest first** - it is a transcript, and reversing it would scramble every "
            "multi-line traceback in it. The same text `sudo awg-panel logs` prints.\n\n"
            "`source` names a service and never a unit: the systemd unit is worked out on "
            "the server, so no unit name from a query string reaches `journalctl`.\n\n"
            "`available: false` with a `reason` is the answer where there is no journal to "
            "read - a container without systemd, a development tree. That is a state and "
            "not a failure, so it is a 200."
        ),
        params=(
            Param(
                "source",
                "Which service. Anything else answers `available: false`.",
                values=("panel", "collector", "tunnel"),
                default="panel",
            ),
            Param("lines", "1-1000.", kind="integer", default=200),
        ),
        result={
            "source": "collector",
            "unit": "awg-panel-collector",
            "lines": [
                {
                    "at": "2026-08-16T09:14:02Z",
                    "priority": 4,
                    "message": "client phone disabled: it has used its whole quota",
                }
            ],
            "available": True,
            "reason": "",
        },
    ),
    # --------------------------------------------------------------- panel
    Op(
        id="settingsGet",
        method="get",
        path="settings",
        tag="Panel",
        summary="Every panel setting",
        description=(
            "The panel's own settings, never the tunnel's. Values are strings in both "
            "directions, whatever they mean."
        ),
        result={
            "webListen": "0.0.0.0",
            "webPort": "2097",
            "webBasePath": "/awg/k2p9x4mt7wq1bz8n5rv3/",
            "tlsCertPath": "",
            "tlsKeyPath": "",
            "configEndpointMode": "ip",
            "configEndpointHost": "",
            "sessionMaxAge": "86400",
            "loginRateLimit": "5",
            "theme": "system",
            "language": "en",
            "trafficPollSec": "2",
            "onlineThresholdSec": "180",
            "enforceIntervalSec": "60",
            "shaperOn": "0",
            "shaperDefaultDownMbps": "0",
            "shaperDefaultUpMbps": "0",
            "shaperUpload": "0",
            "shaperWanIface": "",
        },
    ),
    Op(
        id="settingsUpdate",
        method="put",
        path="settings",
        tag="Panel",
        summary="Change panel settings",
        description=(
            "Changing `webListen`, `webPort`, `webBasePath` or either TLS path rewrites "
            "`/etc/awg-panel.env` and restarts the web service about two seconds later - "
            "late enough that this response still reaches the caller, and after that the "
            "old address stops answering.\n\n"
            "`url` is the whole address to reconnect at, and the host in it is not always "
            "the one you asked on: turning TLS on answers with the name on the "
            "certificate, because the address a panel is administered at is usually one no "
            "certificate covers.\n\n"
            "A `webPort` that another process is bound to right now is refused with a 400 "
            "naming it, rather than accepted and restarted into. Nothing would answer on "
            "the new address, and the panel is the tool you would fix that with."
        ),
        body={"trafficPollSec": "5", "onlineThresholdSec": "120"},
        body_note="Send only what changes.",
        result={
            "settings": {"trafficPollSec": "5"},
            "needsRestart": False,
            "url": "",
            "warnings": [],
        },
        codes=(("400", "A value was rejected; `errors` names the field."),),
    ),
    Op(
        id="settingsCertificate",
        method="get",
        path="settings/certificate",
        tag="Panel",
        summary="What the TLS certificate covers",
        description=(
            "Read off the file rather than out of the settings, because a renewal changes "
            "the names without anything being saved. `domain` is the name the panel would "
            "write into client configs: the first that is neither a wildcard nor an "
            "address.\n\n"
            "`names` carries DNS names and IP addresses together - a certificate issued "
            'for an address has no DNS name at all, and answers `domain` with `""` '
            "because the address on it is the one the client configs already carry.\n\n"
            "`expiresInDays` is whole days "
            "remaining and goes negative once the certificate has expired; it is worth "
            "watching on the six-day certificates issued for addresses, where a renewal "
            "that stops working is a panel that stops opening within the week.\n\n"
            "No certificate, or one that cannot be parsed, answers with empty strings "
            "rather than an error. `?path=` asks about a file that has been typed and not "
            "saved yet."
        ),
        params=(
            Param("path", "A certificate to ask about instead of the configured one."),
            Param("keyPath", "Its private key, so the pair can be checked together."),
        ),
        result={
            "path": "/etc/ssl/certs/panel.crt",
            "names": ["vpn.example.com", "*.example.com"],
            "domain": "vpn.example.com",
            "expiresInDays": 63,
            "problem": "",
            "keyPath": "/etc/ssl/private/panel.key",
            "keyProblem": "",
        },
    ),
    Op(
        id="backup",
        method="get",
        path="backup",
        tag="Panel",
        summary="Download a backup archive",
        description=(
            "A `.tar.gz` of the configuration directory plus the panel's data directory. "
            "The layout is fixed rather than convenient: it is the one `awg-menu` wrote "
            "before backups moved into the panel, so an archive taken off a server years "
            "ago still restores here. **It contains the server private key and every "
            "client private key.**\n\n"
            "It also contains `db.sqlite3` and the panel's signing key, and that is the "
            "one thing to understand before pointing a token at this route: the database "
            "holds the session table, and a session key *is* the `awgsessionid` cookie "
            "rather than a hash of it. **Whatever fetches an archive can sign in as the "
            "account**, whichever routes it is refused elsewhere. Open to a token all the "
            "same, because a nightly copy off the box is worth having and the archive "
            "already carries every key on the server - but the token that asks is named "
            "in the activity log, and one that has asked should be treated as the "
            "password rather than revoked and forgotten."
        ),
        result="<tar.gz>",
        result_type="application/gzip",
        result_note="A gzipped tar archive of the configuration and the panel database.",
    ),
    Op(
        id="restore",
        method="post",
        path="restore",
        tag="Panel",
        summary="Restore a backup archive",
        description=(
            "`multipart/form-data` with the archive in a field called `file`. Rejected "
            "unless it contains `amneziawg/<iface>.conf`. Stops the interface, extracts, "
            "restarts, and reports what was restored. **The current configuration and "
            "every client are replaced.**\n\n"
            "Session only. The archive carries `db.sqlite3`, and with it the password hash "
            "and the token table - so a token that could restore one could replace the "
            "credentials that authorise it."
        ),
        body="file=@awg-panel-backup.tar.gz",
        body_type="multipart/form-data",
        body_note="One form field, `file`, holding the archive. Not JSON.",
        result={
            "restored": ["amneziawg", "awg-panel"],
            "clients": 12,
            "iface": "awg0",
            "restarting": True,
            "detail": "Restored 12 clients.",
        },
        codes=(
            ("400", "The archive is not one of ours."),
            ("403", "An API token asked."),
        ),
        auth=AUTH_SESSION,
    ),
    Op(
        id="updateCheck",
        method="post",
        path="update/check",
        tag="Panel",
        summary="Is there a newer release",
        description=(
            "Compares the installed version against the latest GitHub release. Never "
            'fails on a network error: it answers `{"checked": false, "reason": ...}` '
            "instead, because a panel that cannot reach GitHub is not a panel that is "
            "broken."
        ),
        body=None,
        result={
            "checked": True,
            "reason": "",
            "current": "1.0.0",
            "latest": "1.1.0",
            "updateAvailable": True,
            "url": "https://github.com/.../releases/tag/v1.1.0",
            "notes": "",
            "publishedAt": "2026-08-10T12:00:00Z",
        },
    ),
    Op(
        id="updateStatus",
        method="get",
        path="update/status",
        tag="Panel",
        summary="Where a running or finished update got to",
        description=(
            "`status` is one of `idle`, `running`, `succeeded`, `failed`, and is the only "
            "field worth branching on: `phase` names the current step for a progress line "
            "and gains new values as the updater does. `log` is the tail of the update's "
            "own log, not the whole of it.\n\n"
            "Read straight off the file the updater writes, which is what makes it "
            "survive its subject: an update restarts this service halfway through, so a "
            "poller simply fails for a few seconds and then reads the rest of the story "
            "out of the same file.\n\n"
            "`unavailable` is non-empty on a panel that has no updater installed, and is "
            "the sentence to show instead of an update button."
        ),
        body=None,
        result={
            "status": "running",
            "phase": "install",
            "detail": "Installing 1.1.0 - this takes a few minutes",
            "fromVersion": "1.0.0",
            "toVersion": "1.1.0",
            "started": "2026-08-19T09:12:04Z",
            "finished": "",
            "backup": "/var/lib/awg-panel/backups/awg-backup-20260819-091205.tar.gz",
            "log": "==> [09:12:31] Installing 1.1.0 - this takes a few minutes",
            "unavailable": "",
        },
    ),
    Op(
        id="updateApply",
        method="post",
        path="update/apply",
        tag="Panel",
        summary="Install the newest stable release",
        description=(
            "Takes a backup, downloads the release bundle, checks it against the "
            "published `SHA256SUMS`, and re-runs the installer. Config, keys, clients, "
            "accounts and traffic history are kept - it is the same upgrade as re-running "
            "the installer by hand.\n\n"
            "Answers as soon as the updater is running, **not** when it has finished: this "
            "request is served by the service the update restarts, so poll "
            "`update/status` from there. The reply is that endpoint's shape.\n\n"
            '`{"force": true}` reinstalls the newest release even when it is the one '
            "already on the server.\n\n"
            "Session only, and for a wider reason than the rest of that list: this "
            "replaces every line of code on the server from a release fetched over the "
            "internet, so it decides which software the box runs next."
        ),
        body={"force": False},
        result={
            "status": "running",
            "phase": "starting",
            "detail": "Starting the update.",
            "fromVersion": "1.0.0",
            "toVersion": "",
            "started": "2026-08-19T09:12:04Z",
            "finished": "",
            "backup": "",
            "log": "",
            "unavailable": "",
        },
        codes=(
            ("400", "This server has no updater installed."),
            ("403", "An API token asked."),
            ("409", "An update is already running."),
        ),
        auth=AUTH_SESSION,
    ),
    # --------------------------------------------------------- credentials
    Op(
        id="accountUpdate",
        method="post",
        path="settings/account",
        tag="Credentials",
        summary="Change the username, the password, or both",
        description=(
            "`current` is the password proving who is asking. `username` renames the "
            "account and `new` replaces the password; either may be left out, meaning "
            '"leave that half alone", and a request that asks for neither is a 400.\n\n'
            "Other sessions are invalidated by either change and the caller's own "
            "survives both. Locked out afterwards, the way back is a shell on the server: "
            "`sudo awg-panel passwd` finds the account whatever it is now called."
        ),
        body={"current": "...", "username": "operator", "new": "..."},
        result={"authenticated": True, "username": "operator", "otpRequired": False},
        codes=(
            ("400", "The current password is wrong, or the new name is taken."),
            ("403", "An API token asked."),
        ),
        auth=AUTH_SESSION,
    ),
    Op(
        id="totpEnable",
        method="post",
        path="settings/2fa/enable",
        tag="Credentials",
        summary="Enrol an authenticator app",
        description=(
            "Called twice. First with no body, which returns the secret, the "
            '`otpauth://` URI and a QR code; then with `{"code": "123456"}` to '
            "confirm. Nothing is enforced until the second call succeeds.\n\n"
            "A lost device is recovered from the server shell with `sudo awg-panel "
            "reset-2fa`."
        ),
        body={"code": "123456"},
        body_required=False,
        body_note="Omitted on the first call, which is what starts the enrolment.",
        result={
            "secret": "JBSWY3DPEHPK3PXP",
            "provisioningUri": "otpauth://totp/AWG%20Panel:admin?secret=...",
            "qr": "data:image/png;base64,...",
        },
        result_note='The first call returns the enrolment; the second answers `{"enabled": true}`.',
        codes=(
            ("400", "The code was wrong, or there is nothing waiting to be confirmed."),
            ("403", "An API token asked."),
        ),
        auth=AUTH_SESSION,
    ),
    Op(
        id="totpDisable",
        method="post",
        path="settings/2fa/disable",
        tag="Credentials",
        summary="Turn the second factor off",
        description=(
            "Requires the account password, because removing a factor is a change to the "
            "credential. Every enrolled device goes."
        ),
        body={"password": "..."},
        result={"enabled": False},
        codes=(
            ("400", "The password is wrong."),
            ("403", "An API token asked."),
        ),
        auth=AUTH_SESSION,
    ),
    Op(
        id="sessionList",
        method="get",
        path="settings/sessions",
        tag="Credentials",
        summary="Every browser holding a live session",
        description=(
            "The caller's own first. `id` is minted for this listing; the session key "
            "itself is never sent, because it is the value in that browser's cookie. "
            "`browser` and `platform` are read out of the user agent and are a guess, "
            "which is why the raw header comes with them. `lastSeenAt` is written at most "
            "once a minute."
        ),
        result={
            "sessions": [
                {
                    "id": "0d6b6c3e-6f0e-4a8e-9a3e-6b1f2c5d4e7a",
                    "current": True,
                    "createdAt": "2026-08-05T09:14:02Z",
                    "lastSeenAt": "2026-08-05T11:47:00Z",
                    "expiresAt": "2026-08-06T11:47:00Z",
                    "ip": "203.0.113.10",
                    "browser": "Chrome",
                    "platform": "Windows",
                    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) ...",
                }
            ]
        },
        codes=(("403", "An API token asked."),),
        auth=AUTH_SESSION,
    ),
    Op(
        id="sessionRevoke",
        method="delete",
        path="settings/sessions/{id}",
        tag="Credentials",
        summary="End one session",
        description=(
            "The session is deleted, so the browser holding it is anonymous on its next "
            "request. The caller's own is a 400 - use `auth/logout` for that, which is "
            "what leaves this browser knowing it has been signed out."
        ),
        params=(Param("id", "The id from the listing, not a session key.", where="path"),),
        success="204",
        codes=(
            ("400", "That is the caller's own session."),
            ("403", "An API token asked."),
            ("404", "No session of that id on this account."),
        ),
        auth=AUTH_SESSION,
    ),
    Op(
        id="sessionRevokeOthers",
        method="post",
        path="settings/sessions/revoke-others",
        tag="Credentials",
        summary="End every session except this one",
        description="What to reach for after a password change, or after finding a session you do not recognise.",
        body=None,
        result={"ended": 2},
        codes=(("403", "An API token asked."),),
        auth=AUTH_SESSION,
    ),
    Op(
        id="tokenList",
        method="get",
        path="settings/tokens",
        tag="Credentials",
        summary="Every API token this account holds",
        description=(
            'Newest first, expired ones included: the row is the answer to "why did my '
            'deployment start failing on Tuesday", and one that vanished the moment it '
            "stopped working would leave nothing to read.\n\n"
            "The secret is not here and cannot be - the panel stores a SHA-256 of it. "
            "`hint` is its last four characters, enough to match a row against the copy in "
            "a CI configuration and nothing an attacker can use. `expiresIn` is the "
            "window in seconds, which is what `renewOnUse` restores on each use, not what "
            "is left of it."
        ),
        result={"tokens": [_TOKEN_ROW]},
        codes=(("403", "An API token asked."),),
        auth=AUTH_SESSION,
    ),
    Op(
        id="tokenCreate",
        method="post",
        path="settings/tokens",
        tag="Credentials",
        summary="Issue a token",
        description=(
            "`expiresIn` is seconds: at least 300, at most 3650 days, and `0` or omitted "
            "for one that never expires. `renewOnUse` puts the expiry back to the full "
            "window on every use, which needs an expiry to work on.\n\n"
            "`name` left out or sent blank has the server draw one - the same nine "
            "characters a client gets, checked against the names this account already "
            "uses. A token is never nameless: the activity log writes the name beside "
            "everything the token does.\n\n"
            "**The only response in this API that carries a secret**, and it is shown "
            "once. Send it as `Authorization: Bearer awgp_...`."
        ),
        body={"name": "nightly backup", "expiresIn": 2592000, "renewOnUse": False},
        result={"token": _TOKEN_ROW, "secret": "awgp_S3cr3t..."},
        success="201",
        codes=(
            ("400", "`renewOnUse` with no expiry, or a lifetime outside the bounds."),
            ("403", "An API token asked."),
            ("409", '`code: "name_in_use"`: another token already has that name.'),
        ),
        auth=AUTH_SESSION,
    ),
    Op(
        id="tokenUpdate",
        method="put",
        path="settings/tokens/{id}",
        tag="Credentials",
        summary="Rename a token, or change its renewal",
        description=(
            "Deliberately the whole of what may be changed. Rotating the secret is a new "
            "token and an old one to revoke, and the expiry cannot be pushed out by hand, "
            "because an end date that can be moved whenever it approaches is not one."
        ),
        params=(Param("id", "The token to change.", where="path"),),
        body={"name": "ci", "renewOnUse": True},
        result=_TOKEN_ROW,
        codes=(
            ("400", "Neither field was sent."),
            ("403", "An API token asked."),
            ("404", "No token of that id on this account."),
            ("409", '`code: "name_in_use"`: another token already has that name.'),
        ),
        auth=AUTH_SESSION,
    ),
    Op(
        id="tokenRevoke",
        method="delete",
        path="settings/tokens/{id}",
        tag="Credentials",
        summary="Revoke a token",
        description=(
            "The next request presenting it is anonymous. The row is deleted rather than "
            "flagged: a row kept for the record is a hash that still matches a secret "
            "somebody holds."
        ),
        params=(Param("id", "The token to revoke.", where="path"),),
        success="204",
        codes=(
            ("403", "An API token asked."),
            ("404", "No token of that id on this account."),
        ),
        auth=AUTH_SESSION,
    ),
    # -------------------------------------------------------------- system
    Op(
        id="health",
        method="get",
        path="health",
        tag="System",
        summary="Is the panel answering",
        description=(
            "The one route that needs no credential and reads nothing: it is what the "
            "Docker healthcheck polls, and what the settings page waits on while a "
            "restarted service comes back. Both `health` and `health/` answer."
        ),
        result={"ok": True, "version": "1.0.0"},
        auth=AUTH_NONE,
    ),
    Op(
        id="openapi",
        method="get",
        path="openapi.json",
        tag="System",
        summary="This document",
        description=(
            "The whole API as OpenAPI 3.1, which is what the page you are reading is "
            "rendered from. Point a client generator, Postman or Insomnia at it; `servers` "
            "already carries this panel's own address, base path and all, so an import "
            "needs no editing.\n\n"
            "It describes the panel it is served by, so a version that gained an endpoint "
            "hands out a document that has it."
        ),
        result={"openapi": "3.1.0", "info": {"title": "AWG Panel API"}, "paths": {}},
    ),
)


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

# The conventions, for whoever opens the document in a tool rather than in the
# panel. The page renders its own version of this from the UI catalog, in the
# admin's own language; this copy is what a generated client's README gets.
DESCRIPTION = """\
Everything the AWG Panel does, it does through this API: the panel's own
interface is a client of it, and nothing here is reserved for that client.

**Base path.** Every route is served under the panel's secret base path, which
is already in `servers` below. Anything outside it returns a bare 404, so a
scanner learns nothing.

**Authentication.** Either an API token in an `Authorization: Bearer awgp_...`
header, or the session cookie a browser gets from `POST auth/login`. Anything
that is not a browser should use a token: no cookie jar, no CSRF token, no
second factor, and it can be revoked on its own. A token authenticates as the
account and may do everything the panel can **except** touch the credentials
that authorise it - every route tagged Credentials, plus `auth/logout` and
`POST restore`, answers 403 to one. `GET backup` is the limit of that rule and
not an exception to it: the archive carries the session table, so anything that
can download one can sign in as the account. See that operation.

**CSRF.** A mutating request made with the session cookie must carry
`X-CSRFToken` matching the `awgcsrftoken` cookie; `GET auth/session` sets it. A
request authenticated by a bearer token needs none, because nothing can make a
browser attach an `Authorization` header it was not given.

**Case.** JSON is camelCase in both directions. Times are RFC 3339 in UTC
unless the field name ends in a unit, in which case it is a Unix timestamp in
seconds - `lastHandshake` is what the kernel reports.

**Errors.** Always `{"detail": "...", "errors": {"field": "..."}}`, plus a
`code` where a caller needs to branch on the reason rather than the wording.
`503` with `code: "not_configured"` is what every config-reading route answers
where there is no server configuration: an expected state rather than a fault.
`409` with `code: "name_in_use"` is the conflict that is about a name; a `409`
without it says the tunnel subnet has no free address left, which retrying under
another name will never fix.

**Secrets** are never returned by a listing or a status route. Private keys
appear only in a client's config, its QR code, the export archive and a backup,
all of which exist to hand them out.
"""


def document(server_url: str, version: str) -> dict:
    """The whole catalog as an OpenAPI 3.1 document.

    `server_url` is this panel's own API root, absolute and including the base
    path, so a document imported into a tool works without being edited first.
    """
    paths: dict[str, dict] = {}
    for op in CATALOG:
        paths.setdefault(f"/{op.path}", {})[op.method] = op.render()

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "AWG Panel API",
            "version": version,
            "summary": "Manage an AmneziaWG server: its clients, its interface and the panel itself.",
            "description": DESCRIPTION,
        },
        "servers": [{"url": server_url, "description": "This panel."}],
        "tags": [{"name": name, "description": note} for name, note in TAGS],
        "components": {
            "securitySchemes": {
                BEARER: {
                    "type": "http",
                    "scheme": "bearer",
                    "description": (
                        "A token issued under API - Authentication. Send it as "
                        "`Authorization: Bearer awgp_...` on every request. Needs no "
                        "CSRF token and leaves no session behind."
                    ),
                },
                COOKIE: {
                    "type": "apiKey",
                    "in": "cookie",
                    "name": "awgsessionid",
                    "description": (
                        "The cookie `POST auth/login` sets. A mutating request carrying it "
                        "must also send `X-CSRFToken`."
                    ),
                },
            }
        },
        # Token or session, unless an operation says otherwise. Stated at the
        # top as well so a tool that ignores per-operation security still
        # prompts for a credential.
        "security": [{BEARER: []}, {COOKIE: []}],
        "paths": paths,
    }
