# Generated by Django 5.1.15 on 2026-08-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficHourly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_key", models.CharField(db_index=True, max_length=64)),
                ("hour_ts", models.DateTimeField(db_index=True)),
                ("rx", models.BigIntegerField(default=0)),
                ("tx", models.BigIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "traffic hourly",
                "ordering": ["hour_ts"],
                "unique_together": {("public_key", "hour_ts")},
            },
        ),
        migrations.CreateModel(
            name="TrafficSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_key", models.CharField(db_index=True, max_length=64)),
                ("ts", models.DateTimeField(db_index=True)),
                ("delta_rx", models.BigIntegerField(default=0)),
                ("delta_tx", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["ts"],
                "indexes": [
                    models.Index(fields=["public_key", "ts"], name="stats_traff_public__338de4_idx")
                ],
            },
        ),
    ]
